### ISSUE TITLE
How to actually export?

### ISSUE THREAD

**Issue by minthemiddle** [timpritlove/moneymoney#2]
I installed the `*.lua` extension in the respective folder. Other plugins work. But I cannot find a way to actually export the "Buchungen". I tried right click on selected "Buchungen", right click on the account in the left panel, searched in all menus, but with no success.

How can I actually export the selected "Buchungen"?

**Comment by timpritlove** [comment]
1. Select the items to be exported
2. Select Menu "Account -> Export Transactions" ("Konto -> Umsätze exportieren")
3. Select "Buchungssätze (.csv)" from the "Format" popup meni
4. Choose a file name to export
5. Click export

Make sure all transactions have a proper category and metadata assigned

**Comment by minthemiddle** [comment]
Ah, perfect. That'd be a good addition for the readme, actually.
